name: Deploy

on:
  push:
    branches:
      - heroku

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "webstore-multiparadigma" 
          heroku_email: "juanbal2808@gmail.com"
